Send-PSUHarnessMessage -MessageType 'setState' -Data @{
    componentId = 'root-text'
    state = @{
        text = 'Updated from websocket event'
    }
}

Set-PSUHarnessDownload -Id 'sample-download' -FileName 'harness.txt' -Content 'Download generated by the PSU framework harness.'

Send-PSUHarnessMessage -MessageType 'download' -Data @{
    id = 'sample-download'
    fileName = 'harness.txt'
}

@{
    ok = $true
    endpoint = $HarnessContext.EndpointId
    eventName = $HarnessContext.EventName
    eventData = $HarnessContext.EventData
}
